### ISSUE TITLE
move import

### ISSUE THREAD

**Issue by the-one-with-raspberry** [newtykins/calculator#34]
I tried `node App.js`. It says you can't put "`import`" out of modules. Why?
![image](https://user-images.githubusercontent.com/72183318/132462889-aa47e21e-d6f9-4c40-9e3a-512b64425dac.png)

**Comment by newtykins** [comment]
This project uses ES6. Don't `node App.js` - use the scripts defined in the package.json to do things. `yarn start` will run the project on localhost
